### ISSUE TITLE
Unexpected Token Error

### ISSUE THREAD

**Issue by Ghaleonh41** [K3zter/mcp2-save-splitter#1]
Hello!

I am trying to use your program to convert my PS2 Memory Card File so I can use it on my MemCard Pro2, but I am having a problem when I run the split.ps1 script.

Attached is the error that I keep receiving. Note that the huge space at the C:Users location is my user name & I blacked it out.

Any & all help that you can provide would be appreciated.

Thank you in advance!

![Untitled](https://github.com/K3zter/mcp2-save-splitter/assets/78719249/687bda65-0f32-4bc0-b58a-dbb60d946d0b)

**Comment by K3zter** [comment]
Hi,

That's not an error I'm able to replicate sadly - this line is using RegExp to search for a game ID and then in powershell the $Matches.0 should contain the game ID. My best guess is perhaps you are running an older version of powershell?

If you run `$PSVersionTable` it should tell you your current version - mine is 5.1.x and works okay. If yours is an older version - you could try updating to 5.1.

**Comment by Ghaleonh41** [comment]
Hello, K3zter.

Thank you for the response. My PowerShell version is 2.0. I'm updating it to 5.1 as you recommended as we speak.

**Comment by Ghaleonh41** [comment]
Update: Updating PowerShell worked perfectly! Thank you very much!
